import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms and Conditions | BetterMail",
  description: "The terms that apply when you use the BetterMail Chrome extension and this website.",
};

export default function TermsPage() {
  return (
    <div className="legal">
      <h1>Terms and Conditions</h1>
      <p className="updated">Last updated: October 2026</p>

      <section>
        <p>
          These terms apply to the <strong>BetterMail</strong> Chrome extension and this website. By installing or
          using BetterMail you agree to them. If you don&apos;t agree, please don&apos;t use it.
        </p>

        <h2>1. What BetterMail does</h2>
        <p>
          BetterMail is an AI-powered extension that rewrites email drafts you write in Gmail or Outlook, using the
          tone and options you choose. It does not send emails for you. You review each rewrite and decide whether
          to apply and send it.
        </p>

        <h2>2. Your content and your responsibility</h2>
        <ul>
          <li>You own the text you write and the rewrites produced from it.</li>
          <li>
            Rewrites are generated by AI and can be wrong, off-tone or miss context. Always read a rewrite before
            you apply and send it. You are responsible for every email you send.
          </li>
          <li>
            Don&apos;t use BetterMail to produce spam, harassment, fraud, or anything unlawful, or to process
            content you have no right to use.
          </li>
        </ul>

        <h2>3. Privacy</h2>
        <p>
          How text you choose to rewrite is handled is described in our{" "}
          <Link href="/privacy">Privacy Policy</Link>. By using BetterMail you also agree to that policy.
        </p>

        <h2>4. Third-party services</h2>
        <p>
          BetterMail works inside Gmail and Outlook and relies on third-party AI services to generate rewrites.
          Those services have their own terms, and we don&apos;t control their availability. BetterMail isn&apos;t
          affiliated with or endorsed by Google or Microsoft.
        </p>

        <h2>5. Acceptable use</h2>
        <ul>
          <li>Don&apos;t reverse engineer, resell, or misuse the extension or the service behind it.</li>
          <li>Don&apos;t try to disrupt the service or get around any limits that apply to it.</li>
          <li>Don&apos;t use it in a way that breaks Gmail&apos;s, Outlook&apos;s, or the Chrome Web Store&apos;s rules.</li>
        </ul>

        <h2>6. Intellectual property</h2>
        <p>
          The BetterMail name, logo, extension code and website are ours or our licensors&apos;. These terms give
          you a personal, non-exclusive, revocable right to use the extension. They don&apos;t transfer any
          ownership to you.
        </p>

        <h2>7. No warranty</h2>
        <p>
          BetterMail is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;. We don&apos;t promise that it
          will be uninterrupted, error-free, or that rewrites will suit your purpose.
        </p>

        <h2>8. Limitation of liability</h2>
        <p>
          To the extent the law allows, we aren&apos;t liable for indirect or consequential losses, or for loss
          arising from emails you send, or from relying on a rewrite. Nothing in these terms limits liability that
          can&apos;t be limited by law.
        </p>

        <h2>9. Stopping use</h2>
        <p>
          You can stop at any time by uninstalling the extension. We may suspend or end access if these terms are
          broken or if we have to stop offering the service.
        </p>

        <h2>10. Changes</h2>
        <p>
          We may update these terms. The date at the top shows the latest version, and continuing to use BetterMail
          after a change means you accept it.
        </p>

        <h2>11. Contact</h2>
        <p>
          Questions about these terms: <a href="mailto:dev.aayushmaharjan497@gmail.com">dev.aayushmaharjan497@gmail.com</a>
        </p>
      </section>
    </div>
  );
}
